# Grafana datasource configuration for AFAS monitoring
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: Prometheus-Agricultural
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "120s"
      httpMethod: "POST"
      # Custom headers for agricultural-specific queries
      customQueryParameters: "agricultural=true"
    secureJsonData: {}