# Promtail configuration for AFAS log collection
# Collects logs from all AFAS services and forwards to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # AFAS service logs
  - job_name: afas-services
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-services
          __path__: /var/log/afas/*/*.log
    
    pipeline_stages:
      # Parse JSON logs from structured logging
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: logger_name
            message: event
            agricultural_context: agricultural_context
            confidence_score: confidence_score
            question_type: question_type
      
      # Add labels based on log content
      - labels:
          level:
          service:
          agricultural_context:
          question_type:
      
      # Parse agricultural decision logs specially
      - match:
          selector: '{agricultural_context="true"}'
          stages:
            - json:
                expressions:
                  decision_type: decision_type
                  confidence_level: confidence_level
                  expert_validated: expert_validated
            - labels:
                decision_type:
                confidence_level:
                expert_validated:

  # Error logs with special handling
  - job_name: afas-errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-errors
          __path__: /var/log/afas/*/*_errors.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: logger_name
            error_type: error_type
            severity: severity
            message: event
      
      - labels:
          level:
          service:
          error_type:
          severity:

  # Agricultural decision logs
  - job_name: afas-agricultural
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-agricultural
          __path__: /var/log/afas/*/*_agricultural.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            decision_type: decision_type
            confidence_score: confidence_score
            confidence_level: confidence_level
            processing_time: processing_time_seconds
            expert_validated: expert_validated
            agricultural_sources: agricultural_sources
      
      - labels:
          decision_type:
          confidence_level:
          expert_validated:
      
      # Add metrics based on agricultural logs
      - metrics:
          agricultural_decisions_total:
            type: Counter
            description: "Total agricultural decisions logged"
            source: decision_type
            config:
              action: inc
          
          agricultural_confidence_score:
            type: Histogram
            description: "Agricultural decision confidence scores"
            source: confidence_score
            config:
              buckets: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

  # Metrics logs for Prometheus integration
  - job_name: afas-metrics
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-metrics
          __path__: /var/log/afas/*/*_metrics.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            metric_name: metric_name
            metric_value: metric_value
            metric_type: metric_type
            service_name: service_name
      
      - labels:
          metric_name:
          metric_type:
          service_name:

  # User interaction logs
  - job_name: afas-user-interactions
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-user-interactions
          __path__: /var/log/afas/*/user_interactions.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            user_id: user_id
            interaction_type: interaction_type
            question_type: question_type
            session_duration: session_duration_seconds
            recommendation_accepted: recommendation_accepted
      
      - labels:
          interaction_type:
          question_type:
          recommendation_accepted:

  # Data quality logs
  - job_name: afas-data-quality
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-data-quality
          __path__: /var/log/afas/*/data_quality.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            data_source: data_source
            issue_type: issue_type
            severity: severity
            affected_recommendations: affected_recommendations
      
      - labels:
          data_source:
          issue_type:
          severity:

  # External API logs
  - job_name: afas-external-apis
    static_configs:
      - targets:
          - localhost
        labels:
          job: afas-external-apis
          __path__: /var/log/afas/*/external_apis.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            api_name: api_name
            endpoint: endpoint
            response_time: response_time_seconds
            status_code: status_code
            success: success
      
      - labels:
          api_name:
          success:
          status_code: